<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);CS1998;CS8632</NoWarn>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Impostor.Server\Impostor.Server.csproj" />
  </ItemGroup>

</Project>
